### ISSUE TITLE
flaxues can you help me with a plugin ?

### ISSUE THREAD

**Issue by Erkam246** [flaxues/NoDrop#1]

**Comment by Matthww** [comment]
Sure which one?

**Comment by Erkam246** [comment]
Bedwars i have a Bedwars plugin but it give a error can you fix it (php7)

**Comment by Matthww** [comment]
Link?

**Comment by Erkam246** [comment]
Wait

**Comment by erkam2002** [comment]
https://www.dropbox.com/s/hdtffsscw728c4j/BedWars_v1.0.0.phar?dl=0

**Comment by Erkam246** [comment]
Error on line 519 on open chest

**Comment by Erkam246** [comment]
Have you a test server and you can test it

**Comment by Matthww** [comment]
And when does the error come up?

**Comment by Erkam246** [comment]
Have you a test server?

**Comment by Erkam246** [comment]
I can show it

**Comment by Matthww** [comment]
Yeah but it's localhost...

**Comment by Matthww** [comment]
Just say what you do to let it crash or give a error..

**Comment by Erkam246** [comment]
Error

**Comment by Erkam246** [comment]
Undifined method line 519 addwindow
